<a href="https://colab.research.google.com/github/dzeke/ColoradoRiverCollaborate/blob/main/Powell10year.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Import Colorado River reservoir data from Reclamation
## David E. Rosenberg
## February 27, 2024

## Overview
This is a Jupyter Notebook (.ipynb). This document reads daily Reclamation data for Colorado River reservoirs from U.S. Bureau of Reclamation's (Reclamation) web portal https://www.usbr.gov/uc/water/hydrodata/reservoir_data/919/csv/25.csv). Here, as an example, *919* is the code for Lake Powell. And *25* is the code for reservoir evaporation.

First the code reads in the Metadata for all available reservoirs and data fields from the file 'https://raw.githubusercontent.com/dzeke/ColoradoRiverCollaborate/main/Powell10year/AsPython/ReclamationMetaData.csv.' This metadata includes reservoir name, site id, field name, field ids, units of measurement, and so forth.

Second, the code then iterates over all specified reservoirs and reads in the associated data fields.

Third, the code combines data for all the fields into a database (Pandas dataframe). The database has the columns:
    Date_Raw, Value, Reservoir_ID, Reservoir_Name, Field_ID, Field_Name, Units.
    
Fourth, the code then aggregates data to yearly (water year starting Oct 1).

Fifth, the code plots data for different reservoirs and fields. For example:

 + Evaporation
 + Total evaporation for each period of consecutative 10 years

## Directions to Open, Edit, and Run (Windows)
1. Download all the files into a new local folder on your machine or storage device (e.g., c:\users\myfolder).
2. Open a command prompt (c:\).
3. Install the Juptyer server. At the command prompt type:
    >> pip install jupyter
4. Navigate to the folder where this file is stored. For example:
    >> cd C:\users\myfolder
5. Type the command:
    >> jupyter notebook
6. A new webpage will open in your browser with the url *http://localhost:8888/tree.*
7. Select this file from the list -- **PowellDataImport.ipynb**.
8. This page will display.
9. Select the first cell -- e.g., block [19] to run or edit. You should see the follow output:
    >> A list of numbers from 912 to 923. The reservoir codes.
    >> A list of reservoir names and numbers to the right. e.g.
            Blue Mesa Reservoir 16.
                Here, 16 indicates the number of data fields for the reservoir. e.g, Inflow, Storage, Evaporation, etc.
11. Run each successive cell.

## Requested Citation
David E. Rosenberg (2024), “Import Lake Powell Data from Reclamation.” Utah State University. Logan, Utah.
https://github.com/dzeke/ColoradoRiverCollaborate/tree/main/Powell10year/AsPython.

### Pandas Cheat Sheet
Pandas cheat sheet at https://pandas.pydata.org/docs/user_guide/10min.html.

In [8]:
import pandas as pd
import numpy as np
from pandas.api.types import CategoricalDtype

# Add this command on first run of cell
#!pip install plotnine
from plotnine import *
from plotnine.data import mpg
%matplotlib inline

# Show all records for a pandas data frame
pd.set_option('display.max_rows', None)

# Load the meta data from a csv file on Github
#MetaDataAsUrl = 'https://raw.githubusercontent.com/dzeke/ColoradoRiverCollaborate/main/Powell10year/AsPython/ReclamationMetaData.csv'
#MetaDataAsUrl = 'https://github.com/dzeke/ColoradoRiverCollaborate/blob/main/LakePowell10year/AsPython/ReclamationMetaData.csv'
MetaDataAsUrl = 'ReclamationMetaData.csv'
dfMeta = pd.read_csv(MetaDataAsUrl)

#Define the reservoir codes we are interested in for the Upper and Lower Colorado River basins
lResCodes = list(range(912,924,1))  # Taylor Park, Blue Mesa, Morrow Point, Crystal, Fontenelle, Flaming Gorge, Lake Powell, Navajo, Lake Mead,
                                    # Lake Mohave, Lake Havasu

lResCodes = list(range(919)) # Lake Powell, Navajo, Lake Mead

#Filter on the reservoirs in lResCodes - https://www.kdnuggets.com/2022/12/five-ways-conditional-filtering-pandas.html
dfReservoirData = dfMeta.query('site_id.isin(@lResCodes)')
# Reset the indix
dfReservoirData = dfReservoirData.reset_index()

#Count number of fields per reservoir
#dfReservoirFields = pd.DataFrame(dfReservoirData.groupby('site_metadata.site_name').size().reset_index())

#Count number of fields per reservoir and also show the reservoir ID
dfReservoirFields = pd.DataFrame(dfReservoirData.groupby(['site_metadata.site_name', 'site_id']).size().reset_index())

#lReservoirFieldsColNames = list(dfReservoirFields.columns.values)
#print(lReservoirFieldsColNames)
# Change the third column to be Number of Fields
dfReservoirFields.columns = ['Reservoir', 'Site_ID', 'Number of Fields']

print(lResCodes)
print(dfReservoirFields)
print(dfReservoirData)
print()

# Get the column names
lResColumnNames = dfReservoirData.columns
#Subset the list of column names to those we want
#lResColumnsUse = list(lResColumnNames[i] for i in [1, 2, 4, 5, 10, 26, 27, 28, 29, 30, 31, 32] )
lResColumnsUse = list(lResColumnNames[i] for i in [2, 3, 5, 6, 11, 27, 28, 29, 30, 31, 32, 33] )

#print(lResColumnsUse)
print()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918]
                 Reservoir  Site_ID  Number of Fields
0      BLUE MESA RESERVOIR      913                16
1        CRYSTAL RESERVOIR      915                18
2  FLAMING GORGE RESERVOIR      917                17
3     FONTENELLE RESERVOIR      916                15
4   MORROW POINT RESERVOIR      914                18
5    TAYLOR PARK RESERVOIR      912                 9
    index  site_datatype_id  site_id  datatype_id  site_metadata.site_id  \
0       0              1713      912           17                    912
1       1              1786      912           29                    912
2       2              1834      912           30                    912
3       3              1866      912           42                    912
4       4              1914      912           43                    912
5       5              1922      912           49                    912
6       6              2271      912           25                    912
7       7              7599      912           89                    912
8       8             14192      912           47                    912
9       9              1714      913           17                    913
10     10              1770      913           25                    913
11     11              1787      913           29                    913
12     12              1835      913           30                    913
13     13              1847      913           33                    913
14     14              1852      913           34                    913
15     15              1857      913           39                    913
16     16              1867      913           42                    913
17     17              1915      913           43                    913
18     18              1923      913           49                    913
19     19              2259      913           40                    913
20     20              4147      913           46                    913
21     21              4149      913         1197                    913
22     22              4150      913         1198                    913
23     23              7600      913           89                    913
24     24             14191      913           47                    913
25     25              1715      914           17                    914
26     26              1771      914           25                    914
27     27              1788      914           29                    914
28     28              1836      914           30                    914
29     29              1843      914           31                    914
30     30              1845      914           32                    914
31     31              1848      914           33                    914
32     32              1853      914           34                    914
33     33              1858      914           39                    914
34     34              1868      914           42                    914
35     35              1916      914           43                    914
36     36              1924      914           49                    914
37     37              2261      914           40                    914
38     38              4151      914           46                    914
39     39              4153      914         1197                    914
40     40              4154      914         1198                    914
41     41              7601      914           89                    914
42     42             14195      914           47                    914
43     43              1716      915           17                    915
44     44              1789      915           29                    915
45     45              1837      915           30                    915
46     46              1844      915           31                    915
47     47              1846      915           32                    915
48     48              1849      915           33                    915
49     49              1854      915           34                    915
50     50              1859      915           39                    915
51     51              1869      915           42                    915
52     52              1917      915           43                    915
53     53              1925      915           49                    915
54     54              2260      915           40                    915
55     55              2269      915           25                    915
56     56              4155      915           46                    915
57     57              4157      915         1197                    915
58     58              4158      915         1198                    915
59     59              7602      915           89                    915
60     60             14193      915           47                    915
61     61              1710      916           15                    916
62     62              1717      916           17                    916
63     63              1772      916           25                    916
64     64              1790      916           29                    916
65     65              1838      916           30                    916
66     66              1860      916           39                    916
67     67              1870      916           42                    916
68     68              1918      916           43                    916
69     69              1926      916           49                    916
70     70              2257      916           40                    916
71     71              4159      916           46                    916
72     72              4161      916         1197                    916
73     73              4162      916         1198                    916
74     74             14199      916           47                    916
75     75             14200      916           89                    916
76     76              1711      917           15                    917
77     77              1718      917           17                    917
78     78              1773      917           25                    917
79     79              1791      917           29                    917
80     80              1839      917           30                    917
81     81              1850      917           33                    917
82     82              1855      917           34                    917
83     83              1861      917           39                    917
84     84              1871      917           42                    917
85     85              1919      917           43                    917
86     86              1927      917           49                    917
87     87              2258      917           40                    917
88     88              2416      917           46                    917
89     89              4164      917         1197                    917
90     90              4165      917         1198                    917
91     91             14197      917           47                    917
92     92             14198      917           89                    917

    site_metadata.site_name site_metadata.site_common_name  \
0     TAYLOR PARK RESERVOIR                    TAYLOR PARK
1     TAYLOR PARK RESERVOIR                    TAYLOR PARK
2     TAYLOR PARK RESERVOIR                    TAYLOR PARK
3     TAYLOR PARK RESERVOIR                    TAYLOR PARK
4     TAYLOR PARK RESERVOIR                    TAYLOR PARK
5     TAYLOR PARK RESERVOIR                    TAYLOR PARK
6     TAYLOR PARK RESERVOIR                    TAYLOR PARK
7     TAYLOR PARK RESERVOIR                    TAYLOR PARK
8     TAYLOR PARK RESERVOIR                    TAYLOR PARK
9       BLUE MESA RESERVOIR                      BLUE MESA
10      BLUE MESA RESERVOIR                      BLUE MESA
11      BLUE MESA RESERVOIR                      BLUE MESA
12      BLUE MESA RESERVOIR                      BLUE MESA
13      BLUE MESA RESERVOIR                      BLUE MESA
14      BLUE MESA RESERVOIR                      BLUE MESA
15      BLUE MESA RESERVOIR                      BLUE MESA
16      BLUE MESA RESERVOIR                      BLUE MESA
17      BLUE MESA RESERVOIR                      BLUE MESA
18      BLUE MESA RESERVOIR                      BLUE MESA
19      BLUE MESA RESERVOIR                      BLUE MESA
20      BLUE MESA RESERVOIR                      BLUE MESA
21      BLUE MESA RESERVOIR                      BLUE MESA
22      BLUE MESA RESERVOIR                      BLUE MESA
23      BLUE MESA RESERVOIR                      BLUE MESA
24      BLUE MESA RESERVOIR                      BLUE MESA
25   MORROW POINT RESERVOIR                   MORROW POINT
26   MORROW POINT RESERVOIR                   MORROW POINT
27   MORROW POINT RESERVOIR                   MORROW POINT
28   MORROW POINT RESERVOIR                   MORROW POINT
29   MORROW POINT RESERVOIR                   MORROW POINT
30   MORROW POINT RESERVOIR                   MORROW POINT
31   MORROW POINT RESERVOIR                   MORROW POINT
32   MORROW POINT RESERVOIR                   MORROW POINT
33   MORROW POINT RESERVOIR                   MORROW POINT
34   MORROW POINT RESERVOIR                   MORROW POINT
35   MORROW POINT RESERVOIR                   MORROW POINT
36   MORROW POINT RESERVOIR                   MORROW POINT
37   MORROW POINT RESERVOIR                   MORROW POINT
38   MORROW POINT RESERVOIR                   MORROW POINT
39   MORROW POINT RESERVOIR                   MORROW POINT
40   MORROW POINT RESERVOIR                   MORROW POINT
41   MORROW POINT RESERVOIR                   MORROW POINT
42   MORROW POINT RESERVOIR                   MORROW POINT
43        CRYSTAL RESERVOIR                        CRYSTAL
44        CRYSTAL RESERVOIR                        CRYSTAL
45        CRYSTAL RESERVOIR                        CRYSTAL
46        CRYSTAL RESERVOIR                        CRYSTAL
47        CRYSTAL RESERVOIR                        CRYSTAL
48        CRYSTAL RESERVOIR                        CRYSTAL
49        CRYSTAL RESERVOIR                        CRYSTAL
50        CRYSTAL RESERVOIR                        CRYSTAL
51        CRYSTAL RESERVOIR                        CRYSTAL
52        CRYSTAL RESERVOIR                        CRYSTAL
53        CRYSTAL RESERVOIR                        CRYSTAL
54        CRYSTAL RESERVOIR                        CRYSTAL
55        CRYSTAL RESERVOIR                        CRYSTAL
56        CRYSTAL RESERVOIR                        CRYSTAL
57        CRYSTAL RESERVOIR                        CRYSTAL
58        CRYSTAL RESERVOIR                        CRYSTAL
59        CRYSTAL RESERVOIR                        CRYSTAL
60        CRYSTAL RESERVOIR                        CRYSTAL
61     FONTENELLE RESERVOIR                     FONTENELLE
62     FONTENELLE RESERVOIR                     FONTENELLE
63     FONTENELLE RESERVOIR                     FONTENELLE
64     FONTENELLE RESERVOIR                     FONTENELLE
65     FONTENELLE RESERVOIR                     FONTENELLE
66     FONTENELLE RESERVOIR                     FONTENELLE
67     FONTENELLE RESERVOIR                     FONTENELLE
68     FONTENELLE RESERVOIR                     FONTENELLE
69     FONTENELLE RESERVOIR                     FONTENELLE
70     FONTENELLE RESERVOIR                     FONTENELLE
71     FONTENELLE RESERVOIR                     FONTENELLE
72     FONTENELLE RESERVOIR                     FONTENELLE
73     FONTENELLE RESERVOIR                     FONTENELLE
74     FONTENELLE RESERVOIR                     FONTENELLE
75     FONTENELLE RESERVOIR                     FONTENELLE
76  FLAMING GORGE RESERVOIR                  FLAMING GORGE
77  FLAMING GORGE RESERVOIR                  FLAMING GORGE
78  FLAMING GORGE RESERVOIR                  FLAMING GORGE
79  FLAMING GORGE RESERVOIR                  FLAMING GORGE
80  FLAMING GORGE RESERVOIR                  FLAMING GORGE
81  FLAMING GORGE RESERVOIR                  FLAMING GORGE
82  FLAMING GORGE RESERVOIR                  FLAMING GORGE
83  FLAMING GORGE RESERVOIR                  FLAMING GORGE
84  FLAMING GORGE RESERVOIR                  FLAMING GORGE
85  FLAMING GORGE RESERVOIR                  FLAMING GORGE
86  FLAMING GORGE RESERVOIR                  FLAMING GORGE
87  FLAMING GORGE RESERVOIR                  FLAMING GORGE
88  FLAMING GORGE RESERVOIR                  FLAMING GORGE
89  FLAMING GORGE RESERVOIR                  FLAMING GORGE
90  FLAMING GORGE RESERVOIR                  FLAMING GORGE
91  FLAMING GORGE RESERVOIR                  FLAMING GORGE
92  FLAMING GORGE RESERVOIR                  FLAMING GORGE

   site_metadata.description  site_metadata.elevation  site_metadata.lat  ...  \
0                        NaN                   9321.0           38.81844  ...
1                        NaN                   9321.0           38.81844  ...
2                        NaN                   9321.0           38.81844  ...
3                        NaN                   9321.0           38.81844  ...
4                        NaN                   9321.0           38.81844  ...
5                        NaN                   9321.0           38.81844  ...
6                        NaN                   9321.0           38.81844  ...
7                        NaN                   9321.0           38.81844  ...
8                        NaN                   9321.0           38.81844  ...
9                        NaN                   7304.0           38.45305  ...
10                       NaN                   7304.0           38.45305  ...
11                       NaN                   7304.0           38.45305  ...
12                       NaN                   7304.0           38.45305  ...
13                       NaN                   7304.0           38.45305  ...
14                       NaN                   7304.0           38.45305  ...
15                       NaN                   7304.0           38.45305  ...
16                       NaN                   7304.0           38.45305  ...
17                       NaN                   7304.0           38.45305  ...
18                       NaN                   7304.0           38.45305  ...
19                       NaN                   7304.0           38.45305  ...
20                       NaN                   7304.0           38.45305  ...
21                       NaN                   7304.0           38.45305  ...
22                       NaN                   7304.0           38.45305  ...
23                       NaN                   7304.0           38.45305  ...
24                       NaN                   7304.0           38.45305  ...
25                       NaN                   7052.0           38.45191  ...
26                       NaN                   7052.0           38.45191  ...
27                       NaN                   7052.0           38.45191  ...
28                       NaN                   7052.0           38.45191  ...
29                       NaN                   7052.0           38.45191  ...
30                       NaN                   7052.0           38.45191  ...
31                       NaN                   7052.0           38.45191  ...
32                       NaN                   7052.0           38.45191  ...

In [9]:
# Load the data from Reclamation's webservice for each reservoir and each field
#Create a new empty data frame. Rename Reclamation field names to more useful headers."
lColumnsNewName = ['Date_Raw', 'Value', 'Reservoir_ID', 'Field_ID', 'Reservoir_Name', 'Reservoir_CommonName',  'Basin', 'Field_Name', 'Field_CommonName', 'Balance_Component', 'Unit_ID', 'Unit_Name', 'Unit_CommonName', 'Interval']
    
dfAllData = pd.DataFrame(columns = lColumnsNewName)

print(type(dfReservoirData))
#print(dfReservoirData.columns.tolist())
print(f'Number of Columns of dfReservoirData: {len(dfReservoirData.columns)}')
print(f'Number of Rows of dfReservoirData: {len(dfReservoirData)}')

#Select site_id for rows :3
#print(dfReservoirData.index)
#print(dfReservoirData.loc[1])
#print(dfReservoirData.iloc[int(1), 'site_id'])
#

print(pd.DataFrame(lResColumnNames, columns = ['RawName']))

# Creat a data frame with raw and new columns to check correspondence
dfColumnsCheck = pd.DataFrame(list(zip(lColumnsNewName[2:], lResColumnsUse)),
                                   columns = ['NewName', 'RawName'])
#print(f'dfColumnsCheck: {dfColumnsCheck}')

print()

print(dfAllData)

# Set the url for the Reclamation servier with the data. Example for evaporation from Lake Powell
sEvapDataAsUrl = 'https://www.usbr.gov/uc/water/hydrodata/reservoir_data/919/csv/25.csv'

#Loop over the records in the dfReservoirData dataframe - https://www.geeksforgeeks.org/different-ways-to-iterate-over-rows-in-pandas-dataframe/
for i in range(0,18):
#for i in range(len(dfReservoirData)):  
    #Construct the Url from the reservoir id and field id
    #print(df.loc[i, "Name"], df.loc[i, "Age"])
    #dfReservoirData.get('site_id', default = "no_sid")
    #dfReservoirData.get('datatype_id', default = "no_fid")
    try:
        sResID = str(dfReservoirData.loc[i, 'site_id'])
    except KeyError:
        print("Couldn't find a match for the key:", i)

    #sResID = str(dfReservoirData.loc[i, 'site_id'])
    sFieldID = str(dfReservoirData.loc[i, 'datatype_id'])

    #sResID = '919'
    #sFieldID = '25'
    sURL = 'https://www.usbr.gov/uc/water/hydrodata/reservoir_data/' + sResID + '/csv/' + sFieldID + '.csv' 

    print(sURL)
    # Retrieve and move the dataset for the current reservoir and field into a Pandas Dataframe
    try:
        dfCurr = pd.read_csv(sURL)
    except:
        print(f'Not read: sURL')
        continue

    # Change the column names of the first two columns to Date_Raw, Value
    dfCurr.columns = [lColumnsNewName[0], lColumnsNewName[1]]

    #Loop over the remaining columns, transfer meta data from dfReservoirData to current dataframe
    #for j in range(2,4):
    for j in range(2,len(lColumnsNewName)):
        #print(f'{j} - {lColumnsNewName[j]} - {lResColumnsUse[j-2]}')
        #dfReservoirData.get(lResColumnsUse[j-2])
        dfCurr[lColumnsNewName[j]] = dfReservoirData.loc[i, lResColumnsUse[j-2]]
    
    #print(dfCurr.head())

    # Append the current data to the big data frame\n",
    if i == 0:
        dfAllData = dfCurr
    else:
        frames = [dfAllData, dfCurr]
        dfAllData = pd.concat(frames, ignore_index=True)

print(dfAllData.dtypes)
print(dfAllData.head())

<class 'pandas.core.frame.DataFrame'>
Number of Columns of dfReservoirData: 38
Number of Rows of dfReservoirData: 93
                                     RawName
0                                      index
1                           site_datatype_id
2                                    site_id
3                                datatype_id
4                      site_metadata.site_id
5                    site_metadata.site_name
6             site_metadata.site_common_name
7                  site_metadata.description
8                    site_metadata.elevation
9                          site_metadata.lat
10                       site_metadata.longi
11                site_metadata.db_site_code
12               site_metadata.objecttype_id
13             site_metadata.objecttype_name
14                    site_metadata.basin_id
15             site_metadata.hydrologic_unit
16                  site_metadata.river_mile
17                  site_metadata.segment_no
18                    site_metadata.state_id
19                  site_metadata.state_code
20                     site_metadata.usgs_id
21                    site_metadata.nws_code
22                   site_metadata.shef_code
23                      site_metadata.scs_id
24        site_metadata.parent_objecttype_id
25              site_metadata.parent_site_id
26             datatype_metadata.datatype_id
27           datatype_metadata.datatype_name
28    datatype_metadata.datatype_common_name
29  datatype_metadata.physical_quantity_name
30                 datatype_metadata.unit_id
31               datatype_metadata.unit_name
32        datatype_metadata.unit_common_name
33     datatype_metadata.allowable_intervals
34                 datatype_metadata.agen_id
35                   datatype_metadata.cmmnt
36                            last_meas_date
37                             last_meas_val

Empty DataFrame
Columns: [Date_Raw, Value, Reservoir_ID, Field_ID, Reservoir_Name, Reservoir_CommonName, Basin, Field_Name, Field_CommonName, Balance_Component, Unit_ID, Unit_Name, Unit_CommonName, Interval]
Index: []
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/912/csv/17.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/912/csv/29.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/912/csv/30.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/912/csv/42.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/912/csv/43.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/912/csv/49.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/912/csv/25.csv
Not read: sURL
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/912/csv/89.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/912/csv/47.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/913/csv/17.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/913/csv/25.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/913/csv/29.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/913/csv/30.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/913/csv/33.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/913/csv/34.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/913/csv/39.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/913/csv/42.csv
https://www.usbr.gov/uc/water/hydrodata/reservoir_data/913/csv/43.csv
Date_Raw                 object
Value                   float64
Reservoir_ID              int64
Field_ID                  int64
Reservoir_Name           object
Reservoir_CommonName     object
Basin                    object
Field_Name               object
Field_CommonName         object
Balance_Component        object
Unit_ID                   int64
Unit_Name                object
Unit_CommonName          object
Interval                 object
dtype: object
     Date_Raw      Value  Reservoir_ID  Field_ID         Reservoir_Name  \
0  1958-10-01  51571.852           912        17  TAYLOR PARK RESERVOIR
1  1958-10-02  51507.250           912        17  TAYLOR PARK RESERVOIR
2  1958-10-03  51571.852           912        17  TAYLOR PARK RESERVOIR
3  1958-10-04  51571.852           912        17  TAYLOR PARK RESERVOIR
4  1958-10-05  51571.852           912        17  TAYLOR PARK RESERVOIR

  Reservoir_CommonName Basin                      Field_Name Field_CommonName  \
0          TAYLOR PARK    UC  storage, end of period reading          storage
1          TAYLOR PARK    UC  storage, end of period reading          storage
2          TAYLOR PARK    UC  storage, end of period reading          storage
3          TAYLOR PARK    UC  storage, end of period reading          storage
4          TAYLOR PARK    UC  storage, end of period reading          storage

  Balance_Component  Unit_ID  Unit_Name Unit_CommonName Interval
0           storage        1  acre-feet       acre-feet   either
1           storage        1  acre-feet       acre-feet   either
2           storage        1  acre-feet       acre-feet   either
3           storage        1  acre-feet       acre-feet   either
4           storage        1  acre-feet       acre-feet   either

In [10]:
# Now clean the big data frame
# Convert raw date to formal date
dfAllData['date'] = pd.to_datetime(dfAllData['Date_Raw'])

#Add year and month columns
dfAllData['year'] = pd.DatetimeIndex(dfAllData['date']).year
dfAllData['month'] = pd.DatetimeIndex(dfAllData['date']).month
dfAllData['day'] = pd.DatetimeIndex(dfAllData['date']).day
#dfAllData['lastdayofmonth'] = pd.DatetimeIndex(dfAllData['date']).is_month_end
#dfAllData['dayofyear'] = pd.DatetimeIndex(dfAllData['date']).day_of_year
#dfAllData['leapyear'] = pd.DatetimeIndex(dfAllData['date']).is_leap_year
#dfAllData['daysinyear'] = 365
#dfAllData.loc[dfAllData['leapyear'] == True, 'daysinyear'] = dfAllData['daysinyear'] + 1

#Calculate the water year, Increment by 1 year, Months 10, 11, 12
dfAllData['wateryear'] = dfAllData['year']
dfAllData.loc[dfAllData['month'] >= 10, 'wateryear'] = dfAllData['year'] + 1

# Calculate day of water year
#dOct1ofYear = 273  #Day of year where start water year in a non-leap year (Oct 1)
#dfAllData['dOct1ofYear'] = dOct1ofYear
# Calculate day of water year in a leap year, increment dOct1ofYear by 1
#dfAllData.loc[dfAllData['leapyear'] == True, 'dOct1ofYear'] = dfAllData['dOct1ofYear'] + 1

# For a non-Leap year
#Start 1, 2, 3, ... for days of year after dOct1ofYear
# Start 365 - dOct1, 365-dOct1ofYear + 1, ... for days starting in January 1
#dfAllData['dayofwateryear'] = dfAllData['dayofyear'].apply(lambda x: x + 365 - dOct1ofYear if x <= dOct1ofYear else x - dOct1ofYear)

# For a Leap year
# Days before Oct 1
#dfAllData.loc[(bool(dfAllData['leapyear']) == True) and (dfAllData['dayofyear'] <= dfAllData['dOct1ofYear']), 'dayofwateryear'] = dfAllData['dayofyear'] + dfAllData['daysinyear'] - dfAllData['dOct1ofYear']
# Days after Oct 1
#dfAllData.loc[(bool(dfAllData['leapyear']) == True) and (dfAllData['dayofyear'] > dfAllData['dOct1ofYear']) , 'dayofwateryear'] = dfAllData['dayofyear'] - dfAllData['dOct1ofYear']

# Instead try with lamda https://datatofish.com/if-condition-in-pandas-dataframe/
# For Months Oct, Nov, Dec, day of water year starts at 1.
# This statement gives an error
#dfAllData.loc([dfAllData['month'] >= 10, 'dayofwateryear'] = dfAllData['dayofyear'] - dOct1ofYear
print(dfAllData.dtypes)
print(dfAllData.head())

nRows = len(dfAllData)

print(f'Number of rows read: {nRows}')

#Turn the unique reservoir IDs and names into a dataframe to show IDs and Names
dataRes = {'ReservoirID': dfAllData.Reservoir_ID.unique(),
        'Reservoir': dfAllData.Reservoir_CommonName.unique()}
dfReservoirs = pd.DataFrame(dataRes)
print(dfReservoirs)        

#Turn the unique Field IDs and names into a dataframe to show lookup by number
dataFields = {'FieldID': dfAllData.Field_ID.unique(),
              'Field': dfAllData.Field_CommonName.unique()}
dfFields = pd.DataFrame(dataFields)
print(dfFields)

# https://www.geeksforgeeks.org/get-unique-values-from-a-column-in-pandas-dataframe/
#print(f'Unique Reservoirs: {dfAllData.Reservoir_CommonName.unique()}')
#print(f'Unique Fields: {dfAllData.Field_CommonName.unique()}')
#print(f'Unique Field IDs: {dfAllData.Field_ID.unique()}')
#print(dfAllData.head())

Date_Raw                        object
Value                          float64
Reservoir_ID                     int64
Field_ID                         int64
Reservoir_Name                  object
Reservoir_CommonName            object
Basin                           object
Field_Name                      object
Field_CommonName                object
Balance_Component               object
Unit_ID                          int64
Unit_Name                       object
Unit_CommonName                 object
Interval                        object
date                    datetime64[ns]
year                             int32
month                            int32
day                              int32
wateryear                        int32
dtype: object
     Date_Raw      Value  Reservoir_ID  Field_ID         Reservoir_Name  \
0  1958-10-01  51571.852           912        17  TAYLOR PARK RESERVOIR
1  1958-10-02  51507.250           912        17  TAYLOR PARK RESERVOIR
2  1958-10-03  51571.852           912        17  TAYLOR PARK RESERVOIR
3  1958-10-04  51571.852           912        17  TAYLOR PARK RESERVOIR
4  1958-10-05  51571.852           912        17  TAYLOR PARK RESERVOIR

  Reservoir_CommonName Basin                      Field_Name Field_CommonName  \
0          TAYLOR PARK    UC  storage, end of period reading          storage
1          TAYLOR PARK    UC  storage, end of period reading          storage
2          TAYLOR PARK    UC  storage, end of period reading          storage
3          TAYLOR PARK    UC  storage, end of period reading          storage
4          TAYLOR PARK    UC  storage, end of period reading          storage

  Balance_Component  Unit_ID  Unit_Name Unit_CommonName Interval       date  \
0           storage        1  acre-feet       acre-feet   either 1958-10-01
1           storage        1  acre-feet       acre-feet   either 1958-10-02
2           storage        1  acre-feet       acre-feet   either 1958-10-03
3           storage        1  acre-feet       acre-feet   either 1958-10-04
4           storage        1  acre-feet       acre-feet   either 1958-10-05

   year  month  day  wateryear
0  1958     10    1       1959
1  1958     10    2       1959
2  1958     10    3       1959
3  1958     10    4       1959
4  1958     10    5       1959
Number of rows read: 348829
   ReservoirID    Reservoir
0          912  TAYLOR PARK
1          913    BLUE MESA
    FieldID                      Field
0        17                    storage
1        29                     inflow
2        30              inflow volume
3        42              total release
4        43             release volume
5        49             pool elevation
6        89                       area
7        47              delta storage
8        25                evaporation
9        33         unregulated inflow
10       34  unregulated inflow volume
11       39              power release

In [11]:
### Select a reservoir and field to retrieve
resID = [919]

#fieldID = [25] # Evaporation
fieldID = [30]  # Inflow volume
#fieldID = [17]  # Storage
fieldID = [43] # Release volume

# Options to aggregate by time period
AggregateOptions = ['Day', 'Month', 'Year', 'TenYear'] # Aggregate daily data to time interval
# Select the aggregate option to use
Aggregate = AggregateOptions[3]

#Convert fieldID as list to integer
nfieldID = int(''.join(map(str, fieldID)))
print(nfieldID)

#Field IDs where aggregate at monthly, annual and 10-year we want the value at the last time period
lFieldIDsEndofPeriod = [17, 49, 89]
dfFieldsEoP = dfFields.query('FieldID.isin(@lFieldIDsEndofPeriod)').reset_index()

print('These fields we take the end of period value not the sum')
print(dfFieldsEoP.head())

print(f'nfieldID in lFieldIDsEndofPeriod: {nfieldID in lFieldIDsEndofPeriod}')

#Query on the resID and fieldID
dfResField = dfAllData.query('Reservoir_ID.isin(@resID) and Field_ID.isin(@fieldID)').reset_index()

### Further Process the field based on the aggregate option
sField = str(dfResField.Field_CommonName[0])
#sField = sField.capitalize
print(sField)

if Aggregate == AggregateOptions[0]:
    # Daily, return same data frame
    print('Daily value - no aggregation')
    dfResFieldAgg = dfResField
    
elif Aggregate == AggregateOptions[1]:
    # Daily to Monthly
    # Trim months with less than 28 days
    # Calculate number of days/records for each water year
    dfDaysPerMonth = pd.DataFrame(dfResField.groupby(['Reservoir_ID', 'Field_ID', 'Field_CommonName', 'Unit_ID', 'Unit_CommonName', 'Interval', 'wateryear', 'month']).size().reset_index())
    # Rename the column name 0 to DaysPerYear
    dfDaysPerMonth.columns = ['Reservoir_ID', 'Field_ID', 'Field_CommonName', 'Unit_ID', 'Unit_CommonName', 'Interval', 'wateryear', 'month', 'DaysPerMonth']
    # Filter to years with more than 360 days / records
    dfFullMonths = dfDaysPerMonth.query('DaysPerMonth >= 28')

    # Check the full years
    #print(dfDaysPerWaterYear.head)
    #print(dfFullYears.head())
   
    if nfieldID in lFieldIDsEndofPeriod:
        # This field is end-of-period value
        # Take the monthly value as the value on the first day in the month
        print('Monthly end of period value')
        dfWaterYearMonth = dfResField.query('day == 1')

    else:
        # This field is sum over period
        # Aggregate to monthly values
        print('Monthly sum over field')
        dfWaterYearMonth = dfResField.groupby(['Reservoir_ID', 'Field_ID', 'Field_CommonName', 'Unit_ID', 'Unit_CommonName', 'Interval', 'wateryear', 'month'])[['Value']].sum().reset_index()    # Pull value for last day in water use for fields with Intervals 'either'

        # Left join to only include Months with more than 27 days
        #dfAllDataWaterYear = dfFullYears.merge(dfAllDataWaterYear, on='wateryear', how='left')
        dfWaterYearMonth = dfFullMonths.merge(dfWaterYearMonth, on=['Reservoir_ID', 'Field_ID', 'Field_CommonName', 'Unit_ID', 'Unit_CommonName', 'Interval', 'wateryear', 'month'], how='left')
        #print(dfWaterYearMonth)

        # Add the datetime field back in
        # Convert year, month, day as integers to single integer, i.e, YYYYMMDD
        dfWaterYearMonth['dateinteger'] = dfWaterYearMonth['wateryear']*10000 + dfWaterYearMonth['month']*100 + 1
        #Convert the dateinteger to a datetime
        dfWaterYearMonth['date'] = pd.to_datetime(dfWaterYearMonth['dateinteger'], format='%Y%m%d')

    dfResFieldAgg = dfWaterYearMonth
    
else: # Annual or 10-year running sum
    ### First aggregate Daily to Annual
    
    # Trim water years with less than 360 days
    # Calculate number of days/records for each water year
    dfDaysPerWaterYear = pd.DataFrame(dfResField.groupby(['Reservoir_ID', 'Field_ID', 'Field_CommonName', 'Unit_ID', 'Unit_CommonName', 'Interval', 'wateryear']).size().reset_index())
    # Rename the column name 0 to DaysPerYear
    dfDaysPerWaterYear.columns = ['Reservoir_ID', 'Field_ID', 'Field_CommonName', 'Unit_ID', 'Unit_CommonName', 'Interval', 'wateryear', 'DaysPerYear']
    # Filter to years with more than 360 days / records
    dfFullYears = dfDaysPerWaterYear.query('DaysPerYear >= 360')

    if nfieldID in lFieldIDsEndofPeriod:
        # We have a field that reports value at end of the year
        # Take the value on the first day of the first month of the water year (October 1)
        # 'date' field is preserved
        print()
        print('Annual end of period value')
        dfWaterYear = dfResField.query('month == 10 and day == 1')
        #print(dfResField.head())
                #print(dfWaterYear.head())
    else:  
        # Aggregate to annual values
        print()
        print('Annual sum of period value')

        dfWaterYear = dfResField.groupby(['Reservoir_ID', 'Field_ID', 'Field_CommonName', 'Unit_ID', 'Unit_CommonName', 'Interval', 'wateryear'])[['Value']].sum().reset_index()    # Pull value for last day in water use for fields with Intervals 'either'
        
        # Left join to only include Water Years with more than 360 days
        dfWaterYear = dfFullYears.merge(dfWaterYear, on=['Reservoir_ID', 'Field_ID', 'Field_CommonName', 'Unit_ID', 'Unit_CommonName', 'Interval', 'wateryear'], how='left')

        # Add the datetime field back in
        # Convert year and October 1 as integers to single integer, i.e, YYYYMMDD
        dfWaterYear['dateinteger'] = dfWaterYear['wateryear']*10000 + 10*100 + 1
        #Convert the dateinteger to a datetime
        dfWaterYear['date'] = pd.to_datetime(dfWaterYear['dateinteger'], format='%Y%m%d')

    dfResFieldAgg = dfWaterYear

    if Aggregate == AggregateOptions[3]:
        # Calculate a rolling 10-year sum
        df10year = dfWaterYear
        df10year['Value'] = df10year['Value'].rolling(10).sum()

        dfResFieldAgg = df10year

        sField = '10-Year ' + sField
    
# Turn units of acre-feet into million acre-feet if Unit_Name is acre-feet
if dfResFieldAgg['Unit_CommonName'].iloc[0] == 'acre-feet':
    dfResFieldAgg.Value = dfResFieldAgg.Value / 1e6
    dfResFieldAgg.Unit_CommonName = 'million acre-feet'

# Print out returned dataframe
print(dfResFieldAgg.head())
        
#dfEvapWaterYear['date'] = pd.to_datetime(dfEvapWaterYear['wateryear'])

43
These fields we take the end of period value not the sum
   index  FieldID           Field
0      0       17         storage
1      5       49  pool elevation
2      6       89            area
nfieldID in lFieldIDsEndofPeriod: False

KeyError: 0

# Figure 1. Reservoir Field by Year

In [ ]:
# Use matplotlib

import matplotlib.pyplot as plt

#plt.bar(dfResFieldAgg.wateryear, dfResFieldAgg.Value, color = "grey", width = 1)
# Plot instead using the plot date
plt.plot_date(dfResFieldAgg.date, dfResFieldAgg.Value, 'grey')


plt.xlabel('')
plt.ylabel(sField +'\n' + dfResFieldAgg['Unit_CommonName'].iloc[0])
plt.grid(axis = 'y', linestyle = "dotted")

#Use ggplot
###(ggplot(dfEvapWaterYear, aes(x = 'wateryear'))
### + geom_bar(aes(y='evaporation'), color = "grey", fill = "grey", stat="identity")
 # geom_line(aes(y=OneYearRelease, group = 1, color="Release"), size=2) +
#  + scale_color_manual("", values = "grey50")
#  + scale_fill_manual("", values = "grey50")
### + labs(x="", y="Evaporation\n(million acre-feet per year)")

 # + theme(text = element_text(size=20), legend.title=element_blank(), legend.text=element_text(size=18),
#        legend.key = element_blank())
###)

# Next